name: {{ cookiecutter.project_name }}
version: 0.1.0
synopsis: {{ cookiecutter.synopsis }}
description: Please see README.md
maintainer: {{ cookiecutter.full_name }} <{{ cookiecutter.email }}>
license: GPL
github: {{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}
category: {{ cookiecutter.category }}

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src

executables:
  {{ cookiecutter.project_name }}:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - {{ cookiecutter.project_name }}
      - optparse-applicative

tests:
  tasty:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - {{ cookiecutter.project_name}}
      - QuickCheck
      - tasty
      - tasty-hspec
